---
- name: debian | Installing Pre-Reqs
  apt:
    name: "python-pip"
    state: "present"
  become: true
  when: ansible_os_family == "Debian" and  ansible_distribution_version != "20.04"

- name: Ubuntu 20 | Installing Pre-Reqs
  apt:
    name: "python3-pip"
    state: "present"
  become: true
  when: ansible_distribution == "Ubuntu" and ansible_distribution_version == "20.04"
  