---
- name: debian | Installing Pre-Reqs
  apt:
    name: "python-pip"
    state: "present"
  become: true
  when: (ansible_distribution == "Debian") and (discovered_interpreter_python == "/usr/bin/python")

- name: Ubuntu 20 | Installing Pre-Reqs
  apt:
    name: "python3-pip"
    state: "present"
  become: true
  when: (ansible_distribution == "Ubuntu") and (discovered_interpreter_python == "/usr/bin/python3")
  